### ISSUE TITLE
Load Existing Extension - looking for JSON

### ISSUE THREAD

**Issue by mungewell** [GrandFatherADI/TimeDelta#1]
Thanks for writing this, however I don't see the method for installing into the latest 2.4.22 version of Logic. Clicking 'load existing extension' seems to be looking for 'JSON' files, not the 'DLL' that your release zip contains.

Suggestions?

![Screenshot 2024-12-15 132718](https://github.com/user-attachments/assets/f9cc6ae8-c8ac-4154-bfbc-2d4f2efddf9b)

BTW: I am looking for automated the measurement of time between '1PPS' failing and 'DCLS' falling (trigger for scope/analyzer), in order to evaluate jitter. Am I looking the correct place?

**Comment by mungewell** [comment]
I found solution from this page:
https://support.saleae.com/faq/technical-faq/setting-up-developer-directory
![Screenshot 2024-12-15 144040](https://github.com/user-attachments/assets/a6127532-6dee-4126-bec6-6ebfe9e8e649)

This was then available from the __analyser__ tab (not 'measurements'), so I think I am good. Thanks again for writing it.
![Screenshot 2024-12-15 144447](https://github.com/user-attachments/assets/8b67ddd6-4af5-4be2-8de3-8b6c05b80816)

**Comment by GrandFatherADI** [comment]
Glad you got it sorted. It's a year since I worked on this and my recollection of what is involved has grown somewhat hazy!

Best of luck with your jitter measurement - that's exactly the sort of thing TimeDelta was written for.
